spring.application.name=FlightPing

# TELEGRAM
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

# AERODATABOX
aerodatabox.api.key=${AERODATABOX_API_KEY}
aerodatabox.api.host=${AERODATABOX_API_HOST}
aerodatabox.api.base-url=${AERODATABOX_API_BASE_URL}
